ManageCredentials/Controllers/LeadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ManageCredentials.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ManageCredentials.Controllers
{
    [Authorize]
    public class LeadController : Controller
    {
        private readonly UserDbContext userDbContext;
        private readonly IRepository<BusinessLead> lead;
        private readonly ISession session;
        public LeadController(UserDbContext userDbContext, IRepository<BusinessLead> ld, IHttpContextAccessor httpContextAccessor)
        {
            this.userDbContext = userDbContext;
            lead = ld;
            session = httpContextAccessor.HttpContext.Session;
        }
        public IActionResult Create()
        {
            ViewBag.CreateMode = true;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(BusinessLead model)
        {
            if (ModelState.IsValid)
            {
                userDbContext.Lead.Add(model);
                await userDbContext.SaveChangesAsync();
                session.SetString("Success", "Successfully Created");
                return RedirectToAction("Dashboard","Home");
            }
            return View(model);
        }
        public IActionResult Edit(int id)
        {
            ViewBag.CreateMode = false;
            return View("Create",lead.Get(id));
        }
        [HttpPost]
        public IActionResult Edit(BusinessLead model)
        {
            lead.Update(model);
            session.SetString("Success", "Editted Sucessfully");
           
            return RedirectToAction("Dashboard", "Home");
        }
        public IActionResult Delete(int id)
        {
            lead.Delete(id);
            session.SetString("Success", "Deleted Successfully");
            return RedirectToAction("Dashboard", "Home");
        }
        public IActionResult Detail(int id)
        {
            return View(lead.Get(id));
        }
    }
}

ManageCredentials/Views/Lead/Create.cshtml
@model BusinessLead
@{
    ViewData["Title"] = ViewBag.CreateMode ? "Create" : "Edit";
}
@Html.Partial("_HeaderPartial")

<div class="container">
    <h3 class="text-center">Create Lead</h3>
    <form asp-controller="Lead" asp-action="@(ViewBag.CreateMode ? "Create" : "Edit")" method="post">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 total-data">
                <div class="form-group">
                    <label class="control-label" asp-for="@Model.Title"></label>
                    <input class="form-control" placeholder="Enter Title" asp-for="@Model.Title" />
                    <span class="text-danger" asp-validation-for="@Model.Title"></span>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="@Model.Email"></label>
                        <input class="form-control" placeholder="Enter Email" asp-for="@Model.Email" />
                        <span class="text-danger" asp-validation-for="@Model.Email"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="@Model.Phone"></label>
                        <input class="form-control" placeholder="Enter Phone" asp-for="@Model.Phone" />
                        <span class="text-danger" asp-validation-for="@Model.Phone"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="@Model.Contact"></label>
                        <input class="form-control" placeholder="Enter Contact" asp-for="@Model.Contact" />
                        <span class="text-danger" asp-validation-for="@Model.Contact"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="@Model.Status"></label>
                        <input class="form-control" placeholder="Enter Status" asp-for="@Model.Status" />
                        <span class="text-danger" asp-validation-for="@Model.Status"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="@Model.Phase"></label>
                        <select class="form-control" asp-for="@Model.Phase" asp-items="@Html.GetEnumSelectList<BusinessLead.Phases>()"></select>
                        <span class="text-danger" asp-validation-for="@Model.Phase"></span>
                    </div>

                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="@Model.Country"></label>
                        <select class="form-control" asp-for="@Model.Country" asp-items="@Html.GetEnumSelectList<BusinessLead.CountryName>()"></select>
                        <span class="text-danger" asp-validation-for="@Model.Country"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" asp-for="@Model.Description"></label>
                    <textarea style="height: 13rem;" class="form-control" placeholder="Enter Something" asp-for="@Model.Description"></textarea>
                    <span class="text-danger" asp-validation-for="@Model.Description"></span>
                </div>
                <button type="reset" class="btn btn-primary pull-left">Reset</button>
                <button type="submit" class="btn btn-primary pull-right">@(ViewBag.CreateMode ? "Create" : "Edit")</button>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

ManageCredentials/Views/Lead/Detail.cshtml
@model BusinessLead
@{
    ViewData["Title"] = "Detail";
}
@Html.Partial("_HeaderPartial")

<div class="container">
    <h3 class="text-center">Lead Detail</h3>
    <form>
        <div class="row">
            <div class="col-md-6 col-md-offset-3 total-data">
                <div class="form-group">
                    <label class="control-label" asp-for="@Model.Title"></label>
                    <input class="form-control" placeholder="Enter Title" readonly asp-for="@Model.Title" />
                    <span class="text-danger" asp-validation-for="@Model.Title"></span>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="@Model.Email"></label>
                        <input class="form-control" readonly placeholder="Enter Email" asp-for="@Model.Email" />
                        <span class="text-danger" asp-validation-for="@Model.Email"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="@Model.Phone"></label>
                        <input class="form-control" readonly placeholder="Enter Phone" asp-for="@Model.Phone" />
                        <span class="text-danger" asp-validation-for="@Model.Phone"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="@Model.Contact"></label>
                        <input class="form-control" readonly placeholder="Enter Contact" asp-for="@Model.Contact" />
                        <span class="text-danger" asp-validation-for="@Model.Contact"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="@Model.Status"></label>
                        <input class="form-control" readonly placeholder="Enter Status" asp-for="@Model.Status" />
                        <span class="text-danger" asp-validation-for="@Model.Status"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="@Model.Phase"></label>
                        <input class="form-control" readonly asp-for="@Model.Phase" />
                        <span class="text-danger" asp-validation-for="@Model.Phase"></span>
                    </div>

                    <div class="form-group col-md-6">
                        <label class="control-label" asp-for="@Model.Country"></label>
                        <input class="form-control" readonly asp-for="@Model.Country" />
                        <span class="text-danger" asp-validation-for="@Model.Country"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" asp-for="@Model.Description"></label>
                    <textarea style="height: 15rem;" readonly class="form-control" placeholder="Enter Something" asp-for="@Model.Description"></textarea>
                    <span class="text-danger" asp-validation-for="@Model.Description"></span>
                </div>
                <a asp-controller="Home" asp-action="Dashboard" data-toggle="tooltip" title="Go Back" class="btn btn-primary pull-left">Back</a>
            </div>
        </div>
    </form>
</div>