ManageCredentials/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ManageCredentials.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ManageCredentials.Controllers
{
    public class ContactController : Controller
    {
        private IRepository<Contact> repository;
        private readonly ISession session;
        public ContactController(IRepository<Contact> repo,IHttpContextAccessor httpContextAccessor)
        {
            repository = repo;
            this.session = httpContextAccessor.HttpContext.Session;
        }
        public IActionResult Index()
        {
            return View(repository.GetAll());
        }
        //creating a new contact
        public ViewResult Create()
        {
            ViewBag.CreateMode = true;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Contact model)
        {
            if (ModelState.IsValid)
            {
                repository.Create(model);
                session.SetString("Success", "Successfully Created");
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
        //edit the contact
        public ViewResult Edit(int id)
        {
            ViewBag.CreateMode = false;
            return View("Create",repository.Get(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Contact model)
        {
            repository.Update(model);
            session.SetString("Success", "Successfully Editted");
            return RedirectToAction("Index");
        }
        //delete
        public IActionResult Delete(int id)
        {
            repository.Delete(id);
            session.SetString("Success", "Successfully Deleted");
            return RedirectToAction("Index");
        }
        //detail
        public ViewResult Detail(int id)
        {
            return View(repository.Get(id));
        }
    }
}

ManageCredentials/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ManageCredentials.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ManageCredentials/Views/Shared/_Alerts.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    var sessionData = HttpContextAccessor.HttpContext.Session.GetString("Success");
}
@if (sessionData != null)
{
    <div class="Lead-alerts-custom">
        <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Success! <span class="fa fa-check-circle"></span></strong> <br /> @sessionData 
        </div>
    </div>
}

ManageCredentials/Views/Shared/_HeaderPartial.cshtml
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Business Lead</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a asp-controller="Contact" asp-action="Index">Contacts</a></li>
                <li><a asp-controller="Test" asp-action="Index">TagHelpers</a></li>
            </ul>
            
            @await Html.PartialAsync("_LoginPartial")
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

ManageCredentials/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/lib/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/web-fonts-with-css/css/fontawesome-all.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/css/site.css" rel="stylesheet" />



</head>
<body>
    <div>
        @RenderBody()
    </div>
    <script src="~/lib/jQuery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>

    <script src="~/lib/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/js/dataTables.bootstrap.min.js"></script>
    <script src="~/lib/js/app.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>